### ISSUE TITLE
Package for tfsObjectModel2013 Update 4

### ISSUE THREAD

**Issue by codito** [jeremysimmons/chocolatey-packages#1]
Download link: https://visualstudiogallery.msdn.microsoft.com/19311823-5262-4e63-a586-2283384ae3bf

**Comment by jeremysimmons** [comment]
are you asking me to add a new package, or update the [existing 2013 package](https://github.com/jeremysimmons/chocolatey-packages/tree/master/tfs2013objectmodel) to this Update 4 version?

Glad to see someone is using this.

**Comment by codito** [comment]
@jeremysimmons request to update the existing package to 2013.4.

**Comment by jeremysimmons** [comment]
@codito new version pushed. https://chocolatey.org/packages/tfs2013objectmodel/12.0.31101.0 awaiting moderation.

**Comment by codito** [comment]
thanks! :+1:

**Comment by jeremysimmons** [comment]
you're welcome. may I ask what you're using the package for?

**Comment by codito** [comment]
Currently I use it for a side project on tfs (will open source that one real soon :)) and for git-tfs on my dev box.

**Comment by jeremysimmons** [comment]
I'm glad to hear that it's useful to you.
Let me know when you open source your tfs project.
I am working on this: teambuildscreen.codeplex.com
